variable "region"{}
variable "environment"{}
variable "vpc_cider"{}
variable "az1"{}
variable "az2"{}
variable "private_subnet"{}
variable "public_subnet"{}
variable "private_az2_subnet"{}
variable "public_az2_subnet"{}
variable "cidr_blocks"{}
variable "instance_type"{}
variable "key_name"{}
variable "rds_instance_type"{}
variable "engine"{}
variable "db_name"{}
variable "db_username"{}
variable "db_password"{}
variable "bucket_name"{}
variable "acl"{}
variable "vault_name"{}
variable "schedule"{}
variable "backup_name"{}
variable "image_tag_mutable"{}
variable "cluster_name"{}
variable "account_id"{}